### PR TITLE
Original README converted to markdown format

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by asmecher** [comment]
@kant, could you remove the old README document as part of this PR?

**Comment by kant** [comment]
@asmecher I do not know how to remove the old README, because I do not have the attributes to do it. Please, if you know, share the steps!

**Comment by asmecher** [comment]
@kant, are you working with the command-line git client or making these changes through github.com?

**Comment by kant** [comment]
@asmecher Actually, I am making all the PR that I did today, via Github.com

**Comment by asmecher** [comment]
I haven't done this myself, but here are some suggestions: https://help.github.com/en/github/managing-files-in-a-repository/deleting-files

**Comment by kant** [comment]
@asmecher I'm following the steps from the Github link help. Clicked on `Delete` and now I'm getting this message `You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork kant/usageStats, so you can send a pull request.`

**Comment by asmecher** [comment]
Sorry, @kant, I lost track of this and https://github.com/pkp/usageStats/pull/25 -- merging both, thanks!

**Pull request merged**
